id: P60672322
initial_creation_type: ocr
source_metadata:
  volumes:
    1e9fc4bfdc454aa8ba37a4442c91446a:
      base_file: v005.txt
      image_group_id: I1PD95850
      title: དགྱེས་པ་རྡོ་རྗེའི་སྒྲུབ་ཐབས་རིན་པོ་ཆེའི་སྒྲོན་མ།
      total_pages: 2069
      volume_number: 5
